/**
 * Project Manager (API Client)
 * Connects to Python Backend
 */

const API_URL = 'http://localhost:8000';

export interface Task {
    id: string;
    title: string;
    description: string;
    status: 'pending' | 'in_progress' | 'completed' | 'blocked';
    priority: 'low' | 'medium' | 'high' | 'critical';
    estimatedMinutes?: number;
    dependencies: string[];
    tags: string[];
    deadline?: number;
    createdAt: number;
    completedAt?: number;
}

export interface Project {
    id: string;
    name: string;
    description: string;
    tasks: Task[];
    status: 'planning' | 'active' | 'completed' | 'paused';
    progress: number;
    timeline: {
        startDate: number;
        estimatedCompletion: number;
        actualCompletion?: number;
    };
    autoGenerated: boolean;
    documents: string[];
}

export interface DecompositionResult {
    project: Project;
    reasoning: string;
}

export class ProjectManager {

    async createProject(goal: string, deadline?: number): Promise<DecompositionResult> {
        try {
            const response = await fetch(`${API_URL}/projects/create`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    goal,
                    deadline
                })
            });

            if (!response.ok) throw new Error('Failed to create project');
            return await response.json();
        } catch (error) {
            console.error('Project Create Error:', error);
            throw error;
        }
    }

    async getAllProjects(): Promise<Project[]> {
        try {
            const response = await fetch(`${API_URL}/projects`);
            if (!response.ok) return [];
            return await response.json();
        } catch (error) {
            console.error('Get Projects Error:', error);
            return [];
        }
    }

    async getProject(id: string): Promise<Project | undefined> {
        try {
            const response = await fetch(`${API_URL}/projects/${id}`);
            if (!response.ok) return undefined;
            return await response.json();
        } catch (error) {
            console.error('Get Project Error:', error);
            return undefined;
        }
    }
}

export const projectManager = new ProjectManager();
